# Generated by Django 5.2.1 on 2025-06-01 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supply', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloth_name', models.CharField(max_length=100)),
                ('spoiled_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('size', models.CharField(max_length=80)),
                ('colour', models.CharField(max_length=80)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.supplier')),
            ],
        ),
    ]
