name: CI/CD to AWS EC2

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies & run tests
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          python src/manage.py test --verbosity=2

  deploy:
    needs: build
    if: success()
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add EC2 host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Sync to EC2
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          APP_DIR: ${{ secrets.APP_DIR }}
        run: |
          echo "Syncing to ${SSH_USER}@${SSH_HOST}:${APP_DIR}"
          rsync -avz --exclude '.git*' --exclude 'venv' \
            ./src/ ${SSH_USER}@${SSH_HOST}:${APP_DIR}/

      - name: Remote migrate & restart services
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          APP_DIR:  ${{ secrets.APP_DIR }}
        run: |
          ssh ${SSH_USER}@${SSH_HOST} "\
            set -e && \
            cd ${APP_DIR} && \
            source venv/bin/activate && \
            cd src && \
            pip install -r ${APP_DIR}/requirements.txt && \
            python manage.py migrate --noinput && \
            python manage.py collectstatic --noinput && \
            sudo systemctl restart gunicorn && \
            sudo systemctl restart nginx \
          "


